// Generated by CoffeeScript 1.7.1
var downKey, leftKey, rightKey, upKey;

leftKey = 37;

upKey = 38;

rightKey = 39;

downKey = 40;

$(document).ready(function() {
  var displayGrid, generateGrid;
  $(document).keyup(function(e) {
    var position;
    position = $("#avatar").position();
    switch (e.which) {
      case leftKey:
        if (position.left > 11) {
          $("#avatar").stop().animate({
            left: "-=200"
          });
        }
        break;
      case upKey:
        if (position.top > 11) {
          $("#avatar").stop().animate({
            top: "-=200"
          });
        }
        break;
      case rightKey:
        if (position.left < 411) {
          $("#avatar").stop().animate({
            left: "+=200"
          });
        }
        break;
      case downKey:
        if (position.top < 411) {
          $("#avatar").stop().animate({
            top: "+=200"
          });
        }
    }
    return console.log("left: " + ($("#avatar").css("left")) + "\ntop: " + ($("#avatar").css("left")));
  });
  generateGrid = function(x, y) {
    var arr, i, j, _i, _results;
    arr = [];
    _results = [];
    for (j = _i = 0; 0 <= y ? _i < y : _i > y; j = 0 <= y ? ++_i : --_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (i = _j = 0; 0 <= x ? _j < x : _j > x; i = 0 <= x ? ++_j : --_j) {
          _results1.push(arr.push([i, j]));
        }
        return _results1;
      })());
    }
    return _results;
  };
  console.log(generateGrid(3, 3));
  displayGrid = function(grid) {
    var collum, row, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = grid.length; _i < _len; _i++) {
      row = grid[_i];
      _results.push((function() {
        var _j, _len1, _results1;
        _results1 = [];
        for (_j = 0, _len1 = row.length; _j < _len1; _j++) {
          collum = row[_j];
          _results1.push($(".container").append("<div id='box" + collum + "'></div>"));
        }
        return _results1;
      })());
    }
    return _results;
  };
  return displayGrid(generateGrid(3, 3));
});
